Improve publish script
- Add some build options
- Fix mac app notarization process

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -23,8 +23,8 @@ function export_iOS_app {
     TEAM_ID=$TEAM_ID \
     -exportArchive \
     -archivePath $archive \
-    -exportPath "$export_path" \
-    -exportOptionsPlist "$export_options"
+    -exportPath $export_path \
+    -exportOptionsPlist $export_options
 }
 
 function export_macOS_app {
@@ -36,13 +36,16 @@ function export_macOS_app {
   <plist version=\"1.0\">
     <dict>
       <key>destination</key>
-      <string>upload</string>
+      <string>export</string>
 
       <key>method</key>
       <string>development</string>
 
       <key>signingStyle</key>
-      <string>automatic</string>
+      <string>manual</string>
+
+      <key>signingCertificate</key>
+      <string>Developer ID Application</string>
 
       <key>teamID</key>
       <string>$TEAM_ID</string>
@@ -54,24 +57,23 @@ function export_macOS_app {
     TEAM_ID=$TEAM_ID \
     -exportArchive \
     -archivePath $archive \
-    -exportPath "$export_path" \
-    -exportOptionsPlist "$export_options"
+    -exportPath $export_path \
+    -exportOptionsPlist $export_options
 
-  set +e
+  echo ">>> Creating bundle for upload..."
 
-  until xcodebuild \
-    TEAM_ID=$TEAM_ID \
-    -exportNotarizedApp \
-    -archivePath $archive \
-    -exportPath "$export_path"
-  do \
-    echo "Notarization failed, retrying in 10 seconds"
-    sleep 10
-  done
+  (cd $export_path \
+    && zip -r SpellingBeePlus.zip SpellingBeePlus.app \
+    && rm -rf SpellingBeePlus.app)
 
-  set -e
+  echo ">>> Notarizing..."
 
-  (cd $export_path && zip -r SpellingBeePlus.zip "SpellingBeePlus.app")
+  xcrun notarytool submit \
+    -p "Personal App Signing" \
+    --verbose \
+    --wait \
+    --timeout 2h \
+    $export_path/SpellingBeePlus.zip
 }
 
 function build_app {
@@ -109,28 +111,84 @@ if [[ -z $TEAM_ID ]]; then
   exit 1
 fi
 
+do_build_ios=1
+do_build_mac=1
+do_publish=1
+do_tag=1
+do_check=1
+
+while getopts "hp:b" options; do
+  case "${options}" in
+    p)
+      platform=${OPTARG}
+      case "${platform}" in
+        mac)
+          do_build_ios=0
+          ;;
+        ios)
+          do_build_mac=0
+          ;;
+        *)
+          echo "unknown platform $platform"
+          exit 1
+        ;;
+      esac
+      ;;
+    b)
+      do_check=0
+      do_publish=0
+      do_tag=0
+      ;;
+    h)
+      echo "usage: $0 [-p platform] [-P] [-T] [-h]"
+      echo "  -p platform: build for platform (mac or ios)"
+      echo "  -b: build-only"
+      echo "  -h: print this message"
+      exit 0
+      ;;
+    *)
+      echo "unknown option"
+      exit 1
+      ;;
+  esac
+done
+
 version=$(./version version)
 
-grep -q $version CHANGELOG.md || (echo "Version $version not found in CHANGELOG.md" && exit 1)
-git diff-index --quiet HEAD || (echo "Project has uncommitted changes" && exit 1)
+if (( $do_check )); then
+  grep -q $version CHANGELOG.md || (echo "Version $version not found in CHANGELOG.md" && exit 1)
+  git diff-index --quiet HEAD || (echo "Project has uncommitted changes" && exit 1)
+fi
 
 echo ">>> Clearing previous builds..."
 rm -rf ./build
 
-build_app iOS
-build_app macOS
+if (( $do_build_ios )); then
+  build_app iOS
+fi
+if (( $do_build_mac )); then
+  build_app macOS
+fi
 
-echo ">>> Copying app to deploy host..."
-echo ""
+if (( $do_publish )); then
+  echo ">>> Copying app to deploy host..."
+  echo ""
 
-scp ./build/export/SpellingBeePlus.ipa $DEPLOY_DEST
-scp ./build/export/SpellingBeePlus.zip $DEPLOY_DEST
-scp CHANGELOG.md $DEPLOY_DEST
+  if [[ -f ./build/export/SpellingBeePlus.ipa ]]; then 
+    scp ./build/export/SpellingBeePlus.ipa $DEPLOY_DEST
+  fi
+  if [[ -f ./build/export/SpellingBeePlus.zip ]]; then 
+    scp ./build/export/SpellingBeePlus.zip $DEPLOY_DEST
+  fi
+  scp CHANGELOG.md $DEPLOY_DEST
+fi
 
-echo ">>> Tagging version $version..."
-echo ""
+if (( $do_tag )); then
+  echo ">>> Tagging version $version..."
+  echo ""
 
-git tag "v$version" HEAD
+  git tag "v$version" HEAD
+fi
 
 echo ""
 echo ">>> Done."
